#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
extract_opstable.py — extract the Obfuz VM opcode table from GameAssembly.dll

The CDPH decryption VM (see cdph_dump.py) dispatches on each program byte
through a 256-entry jump table.  Each entry is an RVA offset; the target is a
small handler stub that implements one of a handful of byte-transformation
templates.  The templates and the per-opcode constants are REGENERATED by the
obfuscator per game build, so this table must be re-extracted whenever
GameAssembly.dll changes.

Usage:
    python3 extract_opstable.py GameAssembly.dll 0x5757b8 [-o opstable.json]

The jump-table RVA (0x5757b8 in the build that shipped with the repo) is found
from the ghidra/IDA decompilation of GameAssembly.dll (decompilation/*.c):

  1. grep for the `DecryptBlock` function — it is the one that decrypts the
     "Hello, HybridCLR" key check (grep 'Hello, HybridCLR').  It calls the VM
     dispatcher.
  2. In the VM dispatcher body find:
         eax = *(uint *)&DAT_<base> + (ulonglong)*opcode * 4)
         ... + <base>;  goto ...
     the DAT symbol name encodes the table address, e.g. `DAT_1805757b8`
     means the jump table sits at RVA 0x5757b8 (image base 0x180000000).
  3. Pass that RVA here.

Requires: python3 + capstone (`pip install capstone`).
"""

import json
import struct
import sys

from capstone import Cs, CS_ARCH_X86, CS_MODE_64

DEFAULT_IMAGE_BASE = 0x180000000


def parse_pe(path):
    data = open(path, 'rb').read()
    assert data[:2] == b'MZ'
    pe = struct.unpack_from('<I', data, 0x3c)[0]
    assert data[pe:pe + 4] == b'PE\x00\x00'
    nsec = struct.unpack_from('<H', data, pe + 6)[0]
    opt_size = struct.unpack_from('<H', data, pe + 20)[0]
    opt = pe + 24
    image_base = struct.unpack_from('<Q', data, opt + 24)[0]
    sec_start = opt + opt_size
    secs = []
    for i in range(nsec):
        s = sec_start + i * 40
        vaddr = struct.unpack_from('<I', data, s + 12)[0]
        vsize = struct.unpack_from('<I', data, s + 8)[0]
        p_raw = struct.unpack_from('<I', data, s + 20)[0]
        secs.append((vaddr, vsize, p_raw))

    def rva2off(rva):
        for vaddr, vsize, p_raw in secs:
            if vaddr <= rva < vaddr + max(vsize, 1):
                return p_raw + (rva - vaddr)
        return None
    return data, image_base, rva2off


def disasm_stub(data, rva2off, image_base, start, end):
    off = rva2off(start - image_base)
    code = data[off:off + (end - start) + 8]
    md = Cs(CS_ARCH_X86, CS_MODE_64)
    out = []
    for ins in md.disasm(code, start):
        out.append((ins.mnemonic, ins.op_str))
        if ins.mnemonic == 'jmp':
            out.append(('<<jmp>>', ins.op_str))
            break
    return out


def koff(opstr):
    """Parse `[r8 + K]` / `[r8 + 0xN]` -> K (0 for plain [r8])."""
    import re
    m = re.search(r'\[r8 \+ (0x[0-9a-fA-F]+|\d+)\]', opstr)
    if m:
        return int(m.group(1), 0)
    if '[r8]' in opstr:
        return 0
    return None


def iconst(opstr):
    import re
    m = re.search(r', (0x[0-9a-fA-F]+|\d+)$', opstr)
    return int(m.group(1), 0)


def classify(insns):
    first = insns[0]
    # template ROR : movzx ecx,[r8+K]; mov eax,C1; [sub/add/inc/dec ecx]; jmp <tail>
    if first[0] == 'movzx' and first[1].startswith('ecx, byte ptr [r8'):
        K = koff(first[1])
        C1 = delta = None
        for mn, op in insns:
            if mn == 'mov' and op.startswith('eax, 0x'):
                C1 = int(op[5:], 16)
            elif mn == 'sub' and op.startswith('ecx, '):
                delta = -iconst(op)
            elif mn == 'add' and op.startswith('ecx, '):
                delta = iconst(op)
            elif mn == 'inc' and op == 'ecx':
                delta = 1
            elif mn == 'dec' and op == 'ecx':
                delta = -1
        if '57577f' in insns[-1][1]:
            delta = -2  # shared tail at 0x...577f applies sub ecx,2
        return ('ror', C1, K, delta if delta is not None else 0)

    C1 = int(insns[1][1][5:], 16)
    rest = insns[3:]
    fr = rest[0]
    if fr[0] == 'movzx' and fr[1].startswith('eax, byte ptr [r8'):
        K = koff(fr[1])
        nxt = rest[1]
        if nxt[0] == 'xor' and nxt[1].startswith('al, byte ptr [rdx'):
            return ('xor', C1, K, iconst(rest[2][1]))
        if nxt[0] == 'xor' and nxt[1].startswith('byte ptr [rdx'):
            return ('xor_direct', C1, K, 0)
        if nxt[0] == 'mov' and nxt[1] == 'r9d, edx':
            C2 = iconst(rest[2][1])
            if rest[2][0] == 'sub':
                C2 = -C2
            return ('combined', C1, K, C2)
        if nxt[0] in ('add', 'sub'):
            C2 = iconst(nxt[1])
            if nxt[0] == 'sub':
                C2 = -C2
            return ('swap', C1, K, C2)
        raise ValueError('A-unknown: ' + '; '.join('%s %s' % x for x in insns))
    if fr[0] == 'movzx' and fr[1].startswith('eax, byte ptr [rdx'):
        if rest[1][0] == 'not':
            return ('not_xor', C1, koff(rest[2][1]), 0)
        # block-first XOR: xor al,[r8+K]; xor al,C2
        K = koff(rest[1][1])
        return ('xor', C1, K, iconst(rest[2][1]))
    if fr[0] == 'mov' and fr[1].startswith('eax,'):
        C2 = iconst(fr[1])
        return ('addconst', C1, koff(rest[1][1]), C2)
    raise ValueError('C-unknown: ' + '; '.join('%s %s' % x for x in insns))


def extract(path, jt_rva, image_base=DEFAULT_IMAGE_BASE):
    data, image_base, rva2off = parse_pe(path)
    off = rva2off(jt_rva)
    assert off is not None, 'jump table RVA %#x not in any section' % jt_rva
    entries = struct.unpack_from('<256I', data, off)
    targets = sorted(set(0x180000000 + e if False else (image_base + e) for e in entries))
    OPS = {}
    for op in range(256):
        start = image_base + entries[op]
        end = next((t for t in targets if t > start), start + 0x40)
        insns = disasm_stub(data, rva2off, image_base, start, end)
        OPS[op] = classify(insns)
    return OPS


def main():
    if len(sys.argv) < 3:
        sys.exit(__doc__)
    path = sys.argv[1]
    jt_rva = int(sys.argv[2], 0)
    out = sys.argv[sys.argv.index('-o') + 1] if '-o' in sys.argv else 'opstable.json'
    OPS = extract(path, jt_rva)
    with open(out, 'w') as f:
        json.dump({str(k): v for k, v in OPS.items()}, f)
    from collections import Counter
    c = Counter(k for k, _, _, _ in OPS.values())
    print('extracted %d opcodes -> %s' % (len(OPS), dict(c)))
    print('wrote', out)


if __name__ == '__main__':
    main()
